// Generated by CoffeeScript 1.3.3

/*
Abstract viewport class
Viewport is root layer in any scene
*/


(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['components/graphics/lib/layers/AbstractLayer'], function(AbstractLayer) {
    var AbstractViewport;
    return AbstractViewport = (function(_super) {

      __extends(AbstractViewport, _super);

      function AbstractViewport($parent) {
        this.$parent = $parent;
      }

      return AbstractViewport;

    })(AbstractLayer);
  });

}).call(this);
