// Generated by CoffeeScript 1.3.3

/*
Use this file to load Layer class according to rendering engine specified in settings
*/


(function() {
  "use strict";

  var FN, dependencies, glob, settings;

  FN = Function;

  glob = FN("return this")();

  settings = glob.settings = glob.settings ? glob.settings : {};

  if (!settings.graphicsEngine) {
    settings.graphicsEngine = "dom";
  }

  dependencies = {
    canvas: ["layers/NonDomLayer"],
    dom: ["lib.nayjest/graphics/layers/dom/DomLayer"],
    webgl: [],
    "webgl-2d": ["layers/NonDomLayer"]
  };

  define(dependencies[settings.graphicsEngine], function(Layer) {
    return Layer;
  });

}).call(this);
