// Generated by CoffeeScript 1.3.3

/*
Module DomLayer
@author Vitalii [Nayjest] Stepanenko <gmail@vitaliy.in>
*/


(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['components/graphics/lib/layers/AbstractLayer', 'components/Vector2D/Vector2D', "components/jquery/jquery", "components/underscore/underscore"], function(AbstractLayer, Vector2D) {
    "use strict";

    var DomLayer, defaults, _radInDeg;
    _radInDeg = Math.PI / 180;
    defaults = {
      getCss: function() {
        return {
          outline: '1px dotted gray',
          position: 'absolute',
          padding: 0,
          margin: 0,
          top: 0,
          left: 0
        };
      },
      tag: 'div',
      get$el: function() {
        return $("<" + this.tag + "/>");
      },
      getAttr: function() {
        return {};
      }
    };
    DomLayer = (function(_super) {

      __extends(DomLayer, _super);

      /*
          @option config {Object|null} css DOM Element css
          @option config {Object|null} attr DOM Element attributes
          @option config {Object|null} $el DOM Element wrapped to jQuery object
          @option config {DomElement|jQuery|selector|null} domContainer
      */


      function DomLayer(config) {
        this._createDomElement(config);
        DomLayer.__super__.constructor.call(this, config);
      }

      DomLayer.prototype._createDomElement = function(config) {
        if (config == null) {
          config = {};
        }
        this.$el = config.$el || defaults.get$el();
        if (config.$parentEl) {
          this.setParentEl(config.$parentEl);
        }
        this.$el.css(_.defaults({}, config.css, defaults.getCss()));
        this.$el.attr(_.defaults({}, config.attr, defaults.getAttr()));
        return this.$el.get(0).layer = this;
      };

      /*
          Shows layer
      */


      DomLayer.prototype.show = function() {
        this.$el.show();
        return this;
      };

      DomLayer.prototype.hide = function() {
        this.$el.hide();
        return this;
      };

      DomLayer.prototype._getNonDomLayersOffset = function() {
        var layer, pos, _i, _len, _ref;
        pos = new Vector2D();
        _ref = this.getParents();
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          layer = _ref[_i];
          if (layer instanceof DomLayer) {
            break;
          }
          pos.add(layer.pos);
        }
        return pos;
      };

      DomLayer.prototype._calcDomOffset = function() {
        var a, d, domParentSize, innerTopRightPos, nonDomOffset, parentOffset, res, size, zoom;
        parentOffset = this.$parentEl.offset();
        parentOffset = new Vector2D(parentOffset.left, parentOffset.top);
        zoom = this.getAbsoluteZoom();
        size = this.size.clone().multiplyScalar(zoom);
        domParentSize = new Vector2D(this.$parentEl.width(), this.$parentEl.height());
        innerTopRightPos = domParentSize.substract(size).multiplyScalar(0.5);
        if (this.angle) {
          d = size.magnitude();
          a = Math.PI / 2 - this.angleRad % Math.PI / 2;
          innerTopRightPos.add({
            x: (size.x - d * Math.cos(Math.asin(size.y / d) - a)) / 2,
            y: (size.y - d * Math.sin(a + Math.acos(size.x / d))) / 2
          });
        }
        nonDomOffset = this._getNonDomLayersOffset();
        res = parentOffset.add(innerTopRightPos).add(this.pos.clone().multiplyScalar(zoom)).add(nonDomOffset);
        return {
          left: res.x,
          top: res.y
        };
      };

      DomLayer.prototype.redraw = function() {
        var val;
        val = "rotate(" + this.angle + "deg)";
        this.$el.offset(this._calcDomOffset()).width(this.size.x * this.zoom).height(this.size.y * this.zoom).css({
          "-moz-transform": val,
          "-webkit-transform": val,
          "-o-transform": val,
          transform: val
        });
        return DomLayer.__super__.redraw.call(this);
      };

      DomLayer.prototype.setParentEl = function($parentEl) {
        this.$parentEl = $($parentEl);
        return this.$el.appendTo(this.$parentEl);
      };

      DomLayer.prototype.setParent = function(parent) {
        DomLayer.__super__.setParent.call(this, parent);
        if (parent instanceof DomLayer) {
          this.setParentEl(parent.$el);
        } else {
          if (!this.$parentEl) {
            this.setParentEl($('body'));
          }
        }
        return this;
      };

      DomLayer.prototype.destroy = function() {
        this.$el.detach();
        return DomLayer.__super__.destroy.call(this);
      };

      DomLayer.prototype.getScreenPos = function() {
        var offset;
        offset = this.$el.offset();
        return new Vector2D(offset.left - window.pageXOffset, offset.top - window.pageYOffset);
      };

      DomLayer.prototype.getCenterScreenPos = function() {
        return this.getScreenPos().add(this.size.clone().multiplyScalar(0.5));
      };

      return DomLayer;

    })(AbstractLayer);
    return DomLayer;
  });

}).call(this);
