// Generated by CoffeeScript 1.3.3

/*
Module DomLayer
@author Vitalii [Nayjest] Stepanenko <gmail@vitaliy.in>
*/


(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['components/graphics/lib/layers/dom/AbstractDomLayer', 'components/graphics/lib/layers/Viewport'], function(AbstractDomLayer, Viewport) {
    var DomLayer;
    return DomLayer = (function(_super) {

      __extends(DomLayer, _super);

      DomLayer.prototype.viewportClass = Viewport;

      /*
          @option config {Object|null} css DOM Element css
          @option config {Object|null} attr DOM Element attributes
          @option config {Object|null} $el DOM Element wrapped to jQuery object
          @option config {DomElement|jQuery|selector|null} domContainer
      */


      function DomLayer(config) {
        DomLayer.__super__.constructor.call(this, config);
      }

      return DomLayer;

    })(AbstractDomLayer);
  });

}).call(this);
