// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['lib.nayjest/graphics/layers/dom/DomLayer', 'jquery'], function(DomLayer, $) {
    var DomRectLayer, defaults;
    defaults = {
      color: 'gray',
      borderColor: 'red',
      borderWidth: 1,
      tag: 'div'
    };
    return DomRectLayer = (function(_super) {

      __extends(DomRectLayer, _super);

      function DomRectLayer(config) {
        var options;
        options = $.extend(defaults, config);
        DomRectLayer.__super__.constructor.call(this, options);
        this.setColor(options.color);
        this.setBorderColor(options.borderColor);
      }

      DomRectLayer.prototype.setColor = function(color) {
        this.color = color;
        return this.$el.css('background-color', color);
      };

      DomRectLayer.prototype.setBorderColor = function(color) {
        this.borderColor = color;
        return this.$el.css('border-color', color);
      };

      DomRectLayer.prototype.setBorderWidth = function(width) {
        this.width = width;
        return this.$el.css('border-width', width + 'px');
      };

      return DomRectLayer;

    })(DomLayer);
  });

}).call(this);
