// Generated by CoffeeScript 1.6.2
(function() {
  define([], function() {
    var AbstractFigure;

    return AbstractFigure = (function() {
      function AbstractFigure(layer) {
        this.layer = layer;
      }

      return AbstractFigure;

    })();
  });

}).call(this);
