// Generated by CoffeeScript 1.6.2
(function() {
  define([], function() {
    var dummyFigure, _retNo;

    _retNo = function() {
      return false;
    };
    return dummyFigure = {
      isPointInside: _retNo
    };
  });

}).call(this);
