// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['components/graphics/lib/figures/AbstractFigure', 'components/Vector2D/Vector2D', 'components/geometry/lib/Rectangle'], function(AbstractFigure, Vector2D, Rectangle) {
    var RectangleFigure, _ref;

    return RectangleFigure = (function(_super) {
      __extends(RectangleFigure, _super);

      function RectangleFigure() {
        _ref = RectangleFigure.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      RectangleFigure.prototype.isPointInside = function(point) {
        return Rectangle.isPointInside(point, this.layer.getAbsolutePos(), this.layer.size, this.layer.angleRad);
      };

      return RectangleFigure;

    })(AbstractFigure);
  });

}).call(this);
